# 忽略，打算提供构建好的镜像
services:
  frontend:
    build:
      context: ./frontend  # 指向前端项目代码所在目录
      dockerfile: Dockerfile.prod    # Dockerfile 的名称
    ports:
      - "9003:80"
    restart: always
    depends_on:
      - backend
    networks:
      - backend-network

  backend:
    build:
      context: ./backend  # 指向后端项目代码所在目录
      dockerfile: Dockerfile.prod   # Dockerfile 的名称
    ports:
      - "9000:9000"
    restart: always
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge