# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """AI 服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CodeReview = channel.unary_unary(
                '/ai_service.AIService/CodeReview',
                request_serializer=ai__service__pb2.CodeReviewRequest.SerializeToString,
                response_deserializer=ai__service__pb2.CodeReviewResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/ai_service.AIService/Chat',
                request_serializer=ai__service__pb2.ChatRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.DocumentSearch = channel.unary_unary(
                '/ai_service.AIService/DocumentSearch',
                request_serializer=ai__service__pb2.DocumentSearchRequest.SerializeToString,
                response_deserializer=ai__service__pb2.DocumentSearchResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ai_service.AIService/HealthCheck',
                request_serializer=ai__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ai__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """AI 服务定义
    """

    def CodeReview(self, request, context):
        """代码审查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """智能问答
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DocumentSearch(self, request, context):
        """文档检索
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CodeReview': grpc.unary_unary_rpc_method_handler(
                    servicer.CodeReview,
                    request_deserializer=ai__service__pb2.CodeReviewRequest.FromString,
                    response_serializer=ai__service__pb2.CodeReviewResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=ai__service__pb2.ChatRequest.FromString,
                    response_serializer=ai__service__pb2.ChatResponse.SerializeToString,
            ),
            'DocumentSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.DocumentSearch,
                    request_deserializer=ai__service__pb2.DocumentSearchRequest.FromString,
                    response_serializer=ai__service__pb2.DocumentSearchResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ai__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=ai__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_service.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_service.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """AI 服务定义
    """

    @staticmethod
    def CodeReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AIService/CodeReview',
            ai__service__pb2.CodeReviewRequest.SerializeToString,
            ai__service__pb2.CodeReviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AIService/Chat',
            ai__service__pb2.ChatRequest.SerializeToString,
            ai__service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DocumentSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AIService/DocumentSearch',
            ai__service__pb2.DocumentSearchRequest.SerializeToString,
            ai__service__pb2.DocumentSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AIService/HealthCheck',
            ai__service__pb2.HealthCheckRequest.SerializeToString,
            ai__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
