// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/ai/check/history": {
            "get": {
                "description": "查询手动触发的审核历史记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "手动代码审核"
                ],
                "summary": "获取手动审核历史",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "当前页码",
                        "name": "current",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "状态筛选：0-全部，1-进行中，2-完成，3-失败",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "1703001600",
                        "description": "开始日期",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "1705680000",
                        "description": "结束日期",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ManualCheckHistoryResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ai/check/manual": {
            "post": {
                "description": "用户输入projectId和mergeId，手动触发代码审核",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "手动代码审核"
                ],
                "summary": "手动触发代码审核",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "审核请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ManualCheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ManualCheckResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ai/check/result/{id}": {
            "get": {
                "description": "获取特定审核任务的详细结果",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "手动代码审核"
                ],
                "summary": "获取手动审核结果详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ManualCheckResultResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ai/config": {
            "get": {
                "description": "获取 AI 配置信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI配置"
                ],
                "summary": "获取 AI 配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "更新现有的 AI 配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI配置"
                ],
                "summary": "更新 AI 配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "AI配置信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AIConfigUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的 AI 配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI配置"
                ],
                "summary": "创建 AI 配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "AI配置信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AIConfigCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.AIConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "删除现有的 AI 配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI配置"
                ],
                "summary": "删除AI配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "配置ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AIConfigDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/ai/manager": {
            "get": {
                "description": "获取所有AI管理器列表，服务的集成能力，不允许删除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI配置"
                ],
                "summary": "获取AI管理器列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.AIManager"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ai/merge/check-count": {
            "get": {
                "description": "获取检查数量",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI Code Review"
                ],
                "summary": "获取检查数量",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "开始时间",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "结束时间",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "项目ID",
                        "name": "project_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目命名空间",
                        "name": "project_namespace",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目名称",
                        "name": "project_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "-1未通过 1通过",
                        "name": "passed",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.CheckCountResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ai/merge/problem-chart": {
            "get": {
                "description": "获取问题图表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI Code Review"
                ],
                "summary": "获取问题图表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "开始时间",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "结束时间",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "项目ID",
                        "name": "project_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目命名空间",
                        "name": "project_namespace",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目名称",
                        "name": "project_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "-1未通过 1通过",
                        "name": "passed",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AIProblemCountResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ai/message": {
            "put": {
                "description": "更新AI代码审查记录的人工评分和备注",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI Code Review"
                ],
                "summary": "更新AI Code Review记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "更新信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AIMessageUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的AI代码审查记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI Code Review"
                ],
                "summary": "创建AI Code Review记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "AI代码审查信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AIMessageCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AIMessageCreateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ai/message/list": {
            "post": {
                "description": "获取AI代码审查记录列表，支持多种筛选条件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI Code Review"
                ],
                "summary": "获取AI Code Review列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AIMessageListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AIMessageListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ai/project-namespaces": {
            "get": {
                "description": "获取所有AI消息中的项目命名空间列表（去重），支持时间段筛选，最大允许查询31天的数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI Code Review"
                ],
                "summary": "获取项目命名空间列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "开始时间戳",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "结束时间戳",
                        "name": "end_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ProjectNamespaceListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/gitlab": {
            "get": {
                "description": "获取所有 Gitlab 配置信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gitlab"
                ],
                "summary": "获取 Gitlab 列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "更新现有的 Gitlab Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gitlab"
                ],
                "summary": "更新 Gitlab Token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Gitlab 配置信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.GitlabInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的 Gitlab Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gitlab"
                ],
                "summary": "创建 Gitlab Token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Gitlab 配置信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.GitlabInfoCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定的 Gitlab Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gitlab"
                ],
                "summary": "删除 Gitlab Token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Gitlab Token ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GitlabDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/gitlab/token/projects": {
            "get": {
                "description": "获取所有Gitlab Token的名称和对应的ProjectIds，全量拉取不分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gitlab管理"
                ],
                "summary": "获取Gitlab Token项目信息列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GitlabTokenProjectListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/gitlab/token/refresh": {
            "post": {
                "description": "刷新所有 Gitlab Token 缓存",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gitlab"
                ],
                "summary": "刷新 Gitlab Token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/gitlab/token/{id}": {
            "get": {
                "description": "获取指定的 Gitlab Token 详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gitlab"
                ],
                "summary": "获取 Gitlab Token 详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Gitlab Token ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/login": {
            "post": {
                "description": "用户登录接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回 JWT token 和用户信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/user": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新内部用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "更新内部用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateInnerUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建新的内部用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "创建内部用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateInnerUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除指定用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除用户参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取当前登录用户的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回用户信息和角色列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/resource": {
            "get": {
                "description": "获取资源列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取资源列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ResourceListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "更新资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "更新资源",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "资源",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Resource"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.Resource"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "创建资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "创建资源",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "资源",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Resource"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.Resource"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "删除资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "删除资源",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT认证Token",
                        "name": "jwt_token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.Resource"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/webhook/merge": {
            "post": {
                "description": "处理 GitLab 合并请求的 webhook，自动触发 AI 代码审查与评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Webhook"
                ],
                "summary": "触发 AI 代码审查",
                "parameters": [
                    {
                        "description": "Webhook 触发参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.WebhookBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AIMessageCreateRequest": {
            "type": "object",
            "required": [
                "ai_model",
                "merge_id",
                "merge_url",
                "project_id",
                "result",
                "rule",
                "rule_id"
            ],
            "properties": {
                "ai_model": {
                    "description": "AI模型",
                    "type": "string"
                },
                "merge_id": {
                    "description": "合并请求ID",
                    "type": "integer"
                },
                "merge_url": {
                    "description": "合并请求URL",
                    "type": "string"
                },
                "project_id": {
                    "description": "项目ID",
                    "type": "integer"
                },
                "result": {
                    "description": "AI评论结果",
                    "type": "string"
                },
                "rule": {
                    "description": "规则类型",
                    "type": "integer"
                },
                "rule_id": {
                    "description": "规则ID",
                    "type": "integer"
                }
            }
        },
        "dto.AIMessageCreateResponse": {
            "type": "object",
            "properties": {
                "comments": {
                    "description": "评论内容",
                    "type": "string"
                },
                "id": {
                    "description": "消息ID",
                    "type": "integer"
                }
            }
        },
        "dto.AIMessageItem": {
            "type": "object",
            "properties": {
                "ai_model": {
                    "description": "AI模型",
                    "type": "string"
                },
                "checked_by": {
                    "description": "检查人",
                    "type": "string"
                },
                "create_time": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "human_rating": {
                    "description": "人工评分",
                    "type": "integer"
                },
                "id": {
                    "description": "消息ID",
                    "type": "integer"
                },
                "merge_description": {
                    "description": "合并请求描述",
                    "type": "string"
                },
                "merge_id": {
                    "description": "合并请求ID",
                    "type": "integer"
                },
                "merge_url": {
                    "description": "合并请求URL",
                    "type": "string"
                },
                "passed": {
                    "description": "是否通过",
                    "type": "integer"
                },
                "project_id": {
                    "description": "项目ID",
                    "type": "integer"
                },
                "project_name": {
                    "description": "项目名称",
                    "type": "string"
                },
                "project_namespace": {
                    "description": "项目组",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "result": {
                    "description": "AI评论结果",
                    "type": "string"
                },
                "rule": {
                    "description": "规则类型",
                    "type": "integer"
                },
                "rule_id": {
                    "description": "规则ID",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "integer"
                },
                "update_time": {
                    "description": "更新时间",
                    "type": "integer"
                }
            }
        },
        "dto.AIMessageListRequest": {
            "type": "object",
            "required": [
                "current",
                "page_size"
            ],
            "properties": {
                "current": {
                    "description": "基础参数",
                    "type": "integer",
                    "example": 1
                },
                "end_date": {
                    "description": "结束日期 (时间戳，秒级别)",
                    "type": "integer",
                    "example": 1705680000
                },
                "human_ratings": {
                    "description": "人工评分列表，支持多选",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2
                    ]
                },
                "id": {
                    "description": "筛选参数",
                    "type": "integer",
                    "example": 0
                },
                "page_size": {
                    "description": "每页数量",
                    "type": "integer",
                    "example": 20
                },
                "passed": {
                    "description": "是否通过 -1未通过 1通过",
                    "type": "integer",
                    "example": 0
                },
                "project_ids": {
                    "description": "项目ID列表，支持多选",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2,
                        3
                    ]
                },
                "project_namespaces": {
                    "description": "项目命名空间列表，支持多选",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "frontend",
                        "backend"
                    ]
                },
                "start_date": {
                    "description": "新增筛选参数",
                    "type": "integer",
                    "example": 1703001600
                }
            }
        },
        "dto.AIMessageListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "总数",
                    "type": "integer"
                },
                "data": {
                    "description": "消息列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AIMessageItem"
                    }
                }
            }
        },
        "dto.AIMessageUpdateRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "human_rating": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string"
                }
            }
        },
        "dto.AIProblemCountResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.HumanRatingStat"
                    }
                },
                "period": {
                    "type": "string"
                }
            }
        },
        "dto.CheckCountResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                }
            }
        },
        "dto.CreateInnerUserRequest": {
            "type": "object",
            "required": [
                "name",
                "namespace",
                "password",
                "user"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "job": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "operator": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "role_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "dto.DeleteUserRequest": {
            "type": "object",
            "required": [
                "id",
                "namespace",
                "user"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "namespace": {
                    "type": "string",
                    "example": "default"
                },
                "user": {
                    "type": "string",
                    "example": "test"
                }
            }
        },
        "dto.GitlabDeleteRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "dto.GitlabTokenProjectListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Token项目信息列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GitlabTokenProjectResponse"
                    }
                }
            }
        },
        "dto.GitlabTokenProjectResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Token ID",
                    "type": "integer"
                },
                "name": {
                    "description": "Token名称",
                    "type": "string"
                },
                "project_ids": {
                    "description": "项目ID列表",
                    "type": "string"
                }
            }
        },
        "dto.HumanRatingStat": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                }
            }
        },
        "dto.ManualCheckHistoryItem": {
            "type": "object",
            "properties": {
                "create_time": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "id": {
                    "description": "任务ID",
                    "type": "integer"
                },
                "merge_id": {
                    "description": "合并请求ID",
                    "type": "integer"
                },
                "merge_title": {
                    "description": "合并请求标题",
                    "type": "string"
                },
                "project_id": {
                    "description": "项目ID",
                    "type": "integer"
                },
                "project_name": {
                    "description": "项目名称",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "integer"
                },
                "status_text": {
                    "description": "状态文本",
                    "type": "string"
                },
                "update_time": {
                    "description": "更新时间",
                    "type": "integer"
                }
            }
        },
        "dto.ManualCheckHistoryResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "任务列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ManualCheckHistoryItem"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "dto.ManualCheckRequest": {
            "type": "object",
            "required": [
                "merge_id",
                "project_id"
            ],
            "properties": {
                "ai_model": {
                    "description": "AI模型，可选",
                    "type": "string",
                    "example": "gpt-4"
                },
                "merge_id": {
                    "description": "合并请求ID",
                    "type": "integer",
                    "example": 456
                },
                "project_id": {
                    "description": "项目ID",
                    "type": "integer",
                    "example": 123
                },
                "rule_id": {
                    "description": "规则ID，可选",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.ManualCheckResponse": {
            "type": "object",
            "properties": {
                "estimated_time": {
                    "description": "预估完成时间（秒）",
                    "type": "integer"
                },
                "status": {
                    "description": "任务状态",
                    "type": "string"
                },
                "task_id": {
                    "description": "任务ID",
                    "type": "integer"
                }
            }
        },
        "dto.ManualCheckResultResponse": {
            "type": "object",
            "properties": {
                "ai_model": {
                    "description": "AI模型",
                    "type": "string"
                },
                "create_time": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "id": {
                    "description": "任务ID",
                    "type": "integer"
                },
                "merge_id": {
                    "description": "合并请求ID",
                    "type": "integer"
                },
                "merge_title": {
                    "description": "合并请求标题",
                    "type": "string"
                },
                "merge_url": {
                    "description": "合并请求URL",
                    "type": "string"
                },
                "project_id": {
                    "description": "项目ID",
                    "type": "integer"
                },
                "project_name": {
                    "description": "项目名称",
                    "type": "string"
                },
                "result": {
                    "description": "审核结果",
                    "type": "string"
                },
                "rule_name": {
                    "description": "规则名称",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "integer"
                },
                "update_time": {
                    "description": "更新时间",
                    "type": "integer"
                }
            }
        },
        "dto.MergeRequest": {
            "type": "object",
            "properties": {
                "state": {
                    "type": "string"
                }
            }
        },
        "dto.ObjectAttributes": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "iid": {
                    "type": "integer"
                },
                "merge_url": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "path_with_namespace": {
                    "type": "string"
                },
                "project_id": {
                    "type": "integer"
                },
                "source_branch": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "target_branch": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "dto.ProjectInfo": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "path_with_namespace": {
                    "type": "string"
                }
            }
        },
        "dto.ProjectNamespaceItem": {
            "type": "object",
            "properties": {
                "project_id": {
                    "description": "项目ID",
                    "type": "integer"
                },
                "project_namespace": {
                    "description": "项目命名空间",
                    "type": "string"
                }
            }
        },
        "dto.ProjectNamespaceListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "项目命名空间列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ProjectNamespaceItem"
                    }
                }
            }
        },
        "dto.Resource": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "create_time": {
                    "type": "integer"
                },
                "id": {
                    "description": "根据你的 Resource 字段定义",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "operator": {
                    "type": "string"
                },
                "resource": {
                    "type": "string"
                },
                "update_time": {
                    "type": "integer"
                }
            }
        },
        "dto.ResourceListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Resource"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.UpdateInnerUserRequest": {
            "type": "object",
            "required": [
                "id",
                "namespace"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "job": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "role_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "dto.UserLoginRequest": {
            "type": "object",
            "required": [
                "namespace",
                "password",
                "user"
            ],
            "properties": {
                "namespace": {
                    "type": "string",
                    "example": "acl"
                },
                "password": {
                    "type": "string",
                    "example": "12345678"
                },
                "user": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "dto.WebhookBody": {
            "type": "object",
            "properties": {
                "merge_request": {
                    "$ref": "#/definitions/dto.MergeRequest"
                },
                "object_attributes": {
                    "$ref": "#/definitions/dto.ObjectAttributes"
                },
                "object_kind": {
                    "type": "string"
                },
                "project": {
                    "$ref": "#/definitions/dto.ProjectInfo"
                }
            }
        },
        "model.AIConfig": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "api_url": {
                    "type": "string"
                },
                "create_time": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "description": "1: 启用, 2: 禁用",
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "update_time": {
                    "type": "integer"
                }
            }
        },
        "model.AIConfigCreate": {
            "type": "object",
            "required": [
                "api_key",
                "api_url",
                "model",
                "type"
            ],
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "api_url": {
                    "type": "string"
                },
                "is_active": {
                    "description": "1: 启用, 2: 禁用",
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "description": "预留字段，暂时不使用",
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.AIConfigDelete": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "model.AIConfigUpdate": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "api_url": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "description": "1: 启用, 2: 禁用",
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "description": "UCloud, DeepSeek, OpenAI, Qwen",
                    "type": "string"
                }
            }
        },
        "model.AIManager": {
            "type": "object",
            "properties": {
                "api_url": {
                    "type": "string"
                },
                "create_time": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "update_time": {
                    "type": "integer"
                }
            }
        },
        "model.GitlabInfo": {
            "type": "object",
            "properties": {
                "api": {
                    "type": "string"
                },
                "comment_type": {
                    "description": "1: 普通评论, 2: 行级评论",
                    "type": "integer"
                },
                "create_time": {
                    "type": "integer"
                },
                "expired": {
                    "type": "integer"
                },
                "gitlab_url": {
                    "type": "string"
                },
                "gitlab_version": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "project_ids": {
                    "type": "string"
                },
                "project_ids_synced": {
                    "description": "1: 缓存失败, 2: 缓存中, 3: 缓存成功",
                    "type": "integer"
                },
                "prompt": {
                    "type": "string"
                },
                "rule_check_status": {
                    "description": "1: 启用, 2: 禁用",
                    "type": "integer"
                },
                "source_branch": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "target_branch": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "update_time": {
                    "type": "integer"
                },
                "webhook_name": {
                    "type": "string"
                },
                "webhook_status": {
                    "description": "1: 启用, 2: 禁用",
                    "type": "integer"
                },
                "webhook_url": {
                    "type": "string"
                }
            }
        },
        "model.GitlabInfoCreate": {
            "type": "object",
            "required": [
                "api",
                "name",
                "status",
                "token"
            ],
            "properties": {
                "api": {
                    "type": "string"
                },
                "comment_type": {
                    "description": "1: 普通评论, 2: 行级评论",
                    "type": "integer"
                },
                "expired": {
                    "type": "integer"
                },
                "gitlab_url": {
                    "type": "string"
                },
                "gitlab_version": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "prompt": {
                    "type": "string"
                },
                "rule_check_status": {
                    "description": "1: 启用, 2: 禁用",
                    "type": "integer"
                },
                "source_branch": {
                    "type": "string"
                },
                "status": {
                    "description": "1: 启用, 2: 禁用",
                    "type": "integer"
                },
                "target_branch": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "webhook_name": {
                    "type": "string"
                },
                "webhook_status": {
                    "description": "1: 启用, 2: 禁用",
                    "type": "integer"
                },
                "webhook_url": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {},
                "message": {
                    "type": "string"
                },
                "ret_code": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9000",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Code Review API",
	Description:      "Code Review API documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
