tags:
- name: Project
  description: "项目组"
- name: Resource 
  description: "权限资源管理"
- name: Role 
  description: "角色管理"
- name: Permission
  description: "权限"
- name: User
  description: "登录注册"
- name: Webhook
  description: "webhook"
- name: AI Manager
  description: "AI 管理"
- name: CommonRule
  description: "通用规则"
- name: CustomRule
  description: "自定义规则"

schemes:
 - https
 - http
